<a href="https://colab.research.google.com/github/JJUN1012/Probability-and-Statistics-with-Python/blob/main/4_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###import necessary packages for study

In [2]:
import numpy as np
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

#check version
print(np.__version__)
print(scipy.__version__)

1.26.4
1.13.1


#4.1 express of vector

In [4]:
v =  np.array([0.61, 0.93, 0.24, 0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [5]:
print(v[0])
print(v[3])

0.61
0.27


###4.1.1 size(dimention, length) of vector

In [6]:
v.shape

(4,)

###4.1.2 subvector

In [7]:
v_sub = v[0:2]#v[0]-v[1]
v_sub

array([0.61, 0.93])

###4.1.3 special vectors
A zero vector is a vector where all elements are zero.

In [8]:
size = 3
zeros = np.zeros(shape = (size,))
zeros

array([0., 0., 0.])

A vector with one element equal to 1 and all others equal to 0 is called a unit vector.

Unit vectors are specially denoted using the $\mathbf{e}$ notation.

$\mathbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$
 $\mathbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$
 $\mathbf{e}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$


In [11]:
e = np.zeros(shape = (3,))

i = 1 #locate 1

e[i] = 1
e

array([0., 1., 0.])

A one vector is a vector where all elements are one.

In [12]:
one = np.ones(shape = (size,))
one

array([1., 1., 1.])

###4.1.4 geometric meaning of vectors

In two or three-dimensional space, vectors can be interpreted as:

* Displacements from one point to another
* Forces acting in a particular direction
* Velocities with both speed and direction
* Any quantity that requires both magnitude and direction to be fully described

###4.1.5 Vector Calculation
####4.1.5.1 Vector Addition
Addition of two vectors of the same size is defined as the sum of their corresponding elements.

$\begin{bmatrix} 1 \\ 3 \end{bmatrix} + \begin{bmatrix} 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 4 \\ 4 \end{bmatrix}$

The addition operation satisfies the commutative law and the associative law.

In [13]:
a = np.array([1, 3])
b = np.array([3, 1])
a + b

array([4, 4])

In [14]:
#commutative law
a + b == b + a

array([ True,  True])

In [15]:
#associative law
d = np.array([1, 2])
(a + b) + d == a + (b + d)

array([ True,  True])

####4.1.5.2 Vector subtraction
$\begin{bmatrix} 3 \\ 1 \end{bmatrix} - \begin{bmatrix} 1 \\ 3 \end{bmatrix} = \begin{bmatrix} 2 \\ -2 \end{bmatrix}$

In [17]:
b - a

array([ 2, -2])