<a href="https://colab.research.google.com/github/JJUN1012/Probability-and-Statistics-with-Python/blob/main/4_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This document is typed with python and $\LaTeX$

###import necessary packages for study

In [ ]:
import numpy as np
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

#check version
print(np.__version__)
print(scipy.__version__)

1.26.4
1.13.1


#4.1 express of vector

In [ ]:
v =  np.array([0.61, 0.93, 0.24, 0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [ ]:
print(v[0])
print(v[3])

0.61
0.27


###4.1.1 size(dimention, length) of vector

In [ ]:
v.shape

(4,)

###4.1.2 subvector

In [ ]:
v_sub = v[0:2]#v[0]-v[1]
v_sub

array([0.61, 0.93])

###4.1.3 special vectors
A zero vector is a vector where all elements are zero.

In [ ]:
size = 3
zeros = np.zeros(shape = (size,))
zeros

array([0., 0., 0.])

A vector with one element equal to 1 and all others equal to 0 is called a unit vector.

Unit vectors are specially denoted using the $\mathbf{e}$ notation.

$\mathbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$
 $\mathbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$
 $\mathbf{e}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$


In [ ]:
e = np.zeros(shape = (3,))

i = 1 #locate 1

e[i] = 1
e

array([0., 1., 0.])

A one vector is a vector where all elements are one.

In [ ]:
one = np.ones(shape = (size,))
one

array([1., 1., 1.])

###4.1.4 geometric meaning of vectors

In two or three-dimensional space, vectors can be interpreted as:

* Displacements from one point to another
* Forces acting in a particular direction
* Velocities with both speed and direction
* Any quantity that requires both magnitude and direction to be fully described

###4.1.5 Vector Calculation
####4.1.5.1 Vector Addition
Addition of two vectors of the same size is defined as the sum of their corresponding elements.

$\begin{bmatrix} 1 \\ 3 \end{bmatrix} + \begin{bmatrix} 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 4 \\ 4 \end{bmatrix}$

The addition operation satisfies the commutative law and the associative law.

In [ ]:
a = np.array([1, 3])
b = np.array([3, 1])
a + b

array([4, 4])

In [ ]:
#commutative law
a + b == b + a

array([ True,  True])

In [ ]:
#associative law
d = np.array([1, 2])
(a + b) + d == a + (b + d)

array([ True,  True])

####4.1.5.2 Vector subtraction
$\begin{bmatrix} 3 \\ 1 \end{bmatrix} - \begin{bmatrix} 1 \\ 3 \end{bmatrix} = \begin{bmatrix} 2 \\ -2 \end{bmatrix}$

In [ ]:
b - a

array([ 2, -2])

####4.1.5.3 Scalar-Vector multiplication
Multiply all elments of a vector by scalar

$\begin{bmatrix} \dfrac{1}{2} \end{bmatrix} \begin{bmatrix} 2 \\ 3 \end{bmatrix} = \begin{bmatrix} 1 \\ 1.5 \end{bmatrix}$  

$\begin{bmatrix} 2 \\ 3 \end{bmatrix} \begin{bmatrix} \dfrac{1}{2} \end{bmatrix} = \begin{bmatrix} 1 \\ 1.5 \end{bmatrix}$  

In [ ]:
alpha = 1/2
a = np.array([2, 3])
alpha * a

array([1. , 1.5])

In [ ]:
#commutative law
a * alpha == alpha * a

array([ True,  True])

In [ ]:
#distributive law
beta = 0.7
(alpha + beta) * a == alpha * a + beta * a

array([ True,  True])

####4.1.5.4 Linear Combination
Linear combination is a fundamental concept in linear algebra that refers to the weighted sum of vectors.

a₁v₁ + a₂v₂ + ... + aₙvₙ

###4.1.6 inner product
$a^Tb = \sum_{i=1}^{n} a_ib_i$

T is a notation for transpose

it can be also expressed with $a \cdot b ,  < a,  b >$

$\begin{bmatrix} -1 \\ 2 \\ 3\end{bmatrix}^T \begin{bmatrix} 1 \\ -2 \\ 4 \end{bmatrix} = sum \begin{bmatrix} -1 \\ -4 \\ 12 \end{bmatrix} = 7$

In [ ]:
a =  np.array([-1, 2, 3])
b =  np.array([1, -2, 4])

print(a * b)
np.sum (a * b)

[-1 -4 12]


7

In [ ]:
#with function
print(np.inner(a, b))
print(np.dot(a, b))

7
7


In [ ]:
#commutative law
np.dot(a, b) == np.dot(b, a)

True

In [ ]:
#associative law
alpha = 0.5
np.dot(alpha * a, b) == alpha * np.dot(a, b)

True

In [ ]:
#distributive law
c = np.array([1, 2, 3])
np.dot(a + b, c) == np.dot(a, c) + np.dot(b, c)

True

some usuage of inner product
1. $1^Ta = a_1 + \ldots +a_n = \sum_{i=1}^{n} a_i$
2. $\frac{1}{n}1^Ta = \frac{1}{n}(a_1 + \ldots + a_n) = \bar{a}$
3. $a^Ta = a^2_1 + \ldots + a^2_n$

In [ ]:
a = np.array([1, 2, 3])
size = len(a)
ones = np.ones(shape=(size, ))
np.dot(ones, a)

6.0

In [ ]:
np.dot(ones, a) / len(a)

2.0

In [ ]:
np.dot(a, a)

14

###4.1.7 Vector norm
This is Euclidean norm of Vector.
Norm means length or magnitude of vector

$||a||_2 = \sqrt{a^Ta} = \sqrt{a^2_1 + \ldots + a^2_n}$

example

$\bigg|\bigg|\begin{bmatrix} 2 \\ 3 \end{bmatrix}\bigg|\bigg|= \sqrt{\begin{bmatrix}2 \\ 3 \end{bmatrix}^T\begin{bmatrix}2 \\ 3 \end{bmatrix}} = \sqrt{sum\begin{bmatrix}4 \\ 9 \end{bmatrix}} = \sqrt{13} = 3.606...$

In [ ]:
a = np.array([2, 3])
la.norm(a)

3.605551275463989

A norm satisfies the following properties.

* $||\beta a|| = |\beta|\,||a||$
* $||a + b|| \leq ||a|| + ||b||$
* $||a|| \geq 0$
* $||a|| = 0 \Rightarrow a = 0$

In [ ]:
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

beta = 0.5
la.norm(beta * a) == np.abs(beta) * la.norm(a)

True

In [ ]:
la.norm(a + b) <= la.norm(a) + la.norm(b)

True

In [ ]:
la.norm(a) >= 0

True

In [ ]:
print(la.norm(np.zeros(shape=(2,))))
a == 0

0.0


True

###4.1.8 Inner product & Norm

$u\cdot v = ||u||\,||v||\,cos\theta$

This formula showes that the inner product is in propotional to length of the vectors and $cos$ of angle between the vectors.

1.   When both of Vectors are heading the same direction($\theta = 0^\circ$), the inner product has the max value.
2.   When two Vectors are perpendicular($\theta=90^\circ$), the inner product is 0.
3.   When two Vectors are heading completely opposite directions($\theta = 180^\circ$), the inner product has the min value.




###4.1.9 Vector linear dependence
It is a funcamental concept in linear algebra that describes the relationship between bectors in a vector space.

A set of vectors ${v_q, v_2, ...,v_n}$ is linearly dependent if there exist scalars $c_1,c_2,...,c_n$, not all zero, such that:

$c_1v_1 + c_2v_2 + ... +c_nv_n = 0$

For example:

$a_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, a_2 = \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix}, a_3 = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}$

Clearly, $a_3 = a_1 + a_2$, therefore the vectors above are linearly dependent.
<br><br>

####Linear independence
In other words, at least one vector in the set can be expressed as a linear combination of the others.

Conversely, a set of vectors is linearly independent if the only solution to:

$c_1v_1 + c_2v_2 + ... + c_nv_n$
is $c_1 = c_2 = ... = c_n = 0$

for example:

$a_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, a_2 = \begin{pmatrix} 0 \\ -1 \\ 0 \end{pmatrix}, a_3 = \begin{pmatrix} -1 \\ 0 \\ 1 \end{pmatrix}$

From $\beta_1a_1 + \beta_2a_2 + \beta_3a_3 = 0$, we have $ \beta+1 - \beta_3 = 0, -\beta_2 = 0,$ and $\beta_3 = 0$.Therefore, all $\beta$ values are 0 and vectors above are linearly independent.


####4.1.9.1 basis

A basis in $n$ linearly independent vectors in $n$ dimensions. In other words, two vectors which are linearly independent in two-dimensional vector space. When there are another vectors, they can be expressend as a linear combination of two other linearly independent vectors.

So, If $n$ dimentional vector $a_1, \ldots,a_n$ is a basis, Any $n$ dimensional vector $x$ can be expressed as a linear combination of bases.

**Example**

Express $x = \begin{bmatrix} 0.3 \\ 0.7 \end{bmatrix}$ as a linear combination of $a1 = \begin{bmatrix} 2 \\ 0 \end{bmatrix}, a2 = \begin{bmatrix} 0 \\ 3 \end{bmatrix}$

<br>Answer:<br>
$\beta_1\begin{bmatrix} 2 \\ 0 \end{bmatrix} + \beta_2\begin{bmatrix} 0 \\ 3 \end{bmatrix} = \begin{bmatrix} 0.3 \\ 0.7 \end{bmatrix}$

So,
$\,2\beta_1 =0.3, 3\beta_2 = 0.7$

Therefore, $\begin{bmatrix} \beta_1 \\ \beta_2 \end{bmatrix} = \begin{bmatrix} \frac{0.3}{2} \\ \frac{0.7}{3} \end{bmatrix}$.