<a href="https://colab.research.google.com/github/JJUN1012/Probability-and-Statistics-with-Python/blob/main/4_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This document is typed with python and $\LaTeX$

###import necessary packages for study

In [2]:
import numpy as np
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

#check version
print(np.__version__)
print(scipy.__version__)

1.26.4
1.13.1


#4.1 express of vector

In [3]:
v =  np.array([0.61, 0.93, 0.24, 0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [4]:
print(v[0])
print(v[3])

0.61
0.27


###4.1.1 size(dimention, length) of vector

In [5]:
v.shape

(4,)

###4.1.2 subvector

In [6]:
v_sub = v[0:2]#v[0]-v[1]
v_sub

array([0.61, 0.93])

###4.1.3 special vectors
A zero vector is a vector where all elements are zero.

In [7]:
size = 3
zeros = np.zeros(shape = (size,))
zeros

array([0., 0., 0.])

A vector with one element equal to 1 and all others equal to 0 is called a unit vector.

Unit vectors are specially denoted using the $\mathbf{e}$ notation.

$\mathbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$
 $\mathbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$
 $\mathbf{e}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$


In [8]:
e = np.zeros(shape = (3,))

i = 1 #locate 1

e[i] = 1
e

array([0., 1., 0.])

A one vector is a vector where all elements are one.

In [9]:
one = np.ones(shape = (size,))
one

array([1., 1., 1.])

###4.1.4 geometric meaning of vectors

In two or three-dimensional space, vectors can be interpreted as:

* Displacements from one point to another
* Forces acting in a particular direction
* Velocities with both speed and direction
* Any quantity that requires both magnitude and direction to be fully described

###4.1.5 Vector Calculation
####4.1.5.1 Vector Addition
Addition of two vectors of the same size is defined as the sum of their corresponding elements.

$\begin{bmatrix} 1 \\ 3 \end{bmatrix} + \begin{bmatrix} 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 4 \\ 4 \end{bmatrix}$

The addition operation satisfies the commutative law and the associative law.

In [10]:
a = np.array([1, 3])
b = np.array([3, 1])
a + b

array([4, 4])

In [11]:
#commutative law
a + b == b + a

array([ True,  True])

In [12]:
#associative law
d = np.array([1, 2])
(a + b) + d == a + (b + d)

array([ True,  True])

####4.1.5.2 Vector subtraction
$\begin{bmatrix} 3 \\ 1 \end{bmatrix} - \begin{bmatrix} 1 \\ 3 \end{bmatrix} = \begin{bmatrix} 2 \\ -2 \end{bmatrix}$

In [13]:
b - a

array([ 2, -2])

####4.1.5.3 Scalar-Vector multiplication
Multiply all elments of a vector by scalar

$\begin{bmatrix} \dfrac{1}{2} \end{bmatrix} \begin{bmatrix} 2 \\ 3 \end{bmatrix} = \begin{bmatrix} 1 \\ 1.5 \end{bmatrix}$  

$\begin{bmatrix} 2 \\ 3 \end{bmatrix} \begin{bmatrix} \dfrac{1}{2} \end{bmatrix} = \begin{bmatrix} 1 \\ 1.5 \end{bmatrix}$  

In [14]:
alpha = 1/2
a = np.array([2, 3])
alpha * a

array([1. , 1.5])

In [15]:
#commutative law
a * alpha == alpha * a

array([ True,  True])

In [16]:
#distributive law
beta = 0.7
(alpha + beta) * a == alpha * a + beta * a

array([ True,  True])

####4.1.5.4 Linear Combination
Linear combination is a fundamental concept in linear algebra that refers to the weighted sum of vectors.

a₁v₁ + a₂v₂ + ... + aₙvₙ

###4.1.6 inner product
$a^Tb = \sum_{i=1}^{n} a_ib_i$

T is a notation for transpose

it can be also expressed with $a \cdot b ,  < a,  b >$

$\begin{bmatrix} -1 \\ 2 \\ 3\end{bmatrix}^T \begin{bmatrix} 1 \\ -2 \\ 4 \end{bmatrix} = sum \begin{bmatrix} -1 \\ -4 \\ 12 \end{bmatrix} = 7$

In [17]:
a =  np.array([-1, 2, 3])
b =  np.array([1, -2, 4])

print(a * b)
np.sum (a * b)

[-1 -4 12]


7

In [18]:
#with function
print(np.inner(a, b))
print(np.dot(a, b))

7
7


In [19]:
#commutative law
np.dot(a, b) == np.dot(b, a)

True

In [20]:
#associative law
alpha = 0.5
np.dot(alpha * a, b) == alpha * np.dot(a, b)

True

In [21]:
#distributive law
c = np.array([1, 2, 3])
np.dot(a + b, c) == np.dot(a, c) + np.dot(b, c)

True

some usuage of inner product
1. $1^Ta = a_1 + \ldots +a_n = \sum_{i=1}^{n} a_i$
2. $\frac{1}{n}1^Ta = \frac{1}{n}(a_1 + \ldots + a_n) = \bar{a}$
3. $a^Ta = a^2_1 + \ldots + a^2_n$

In [22]:
a = np.array([1, 2, 3])
size = len(a)
ones = np.ones(shape=(size, ))
np.dot(ones, a)

6.0

In [23]:
np.dot(ones, a) / len(a)

2.0

In [24]:
np.dot(a, a)

14

###4.1.7 Vector norm
This is Euclidean norm of Vector.
Norm means length or magnitude of vector

$||a||_2 = \sqrt{a^Ta} = \sqrt{a^2_1 + \ldots + a^2_n}$

example

$\bigg|\bigg|\begin{bmatrix} 2 \\ 3 \end{bmatrix}\bigg|\bigg|= \sqrt{\begin{bmatrix}2 \\ 3 \end{bmatrix}^T\begin{bmatrix}2 \\ 3 \end{bmatrix}} = \sqrt{sum\begin{bmatrix}4 \\ 9 \end{bmatrix}} = \sqrt{13} = 3.606...$

In [25]:
a = np.array([2, 3])
la.norm(a)

3.605551275463989

A norm satisfies the following properties.

* $||\beta a|| = |\beta|\,||a||$
* $||a + b|| \leq ||a|| + ||b||$
* $||a|| \geq 0$
* $||a|| = 0 \Rightarrow a = 0$

In [26]:
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

beta = 0.5
la.norm(beta * a) == np.abs(beta) * la.norm(a)

True

In [27]:
la.norm(a + b) <= la.norm(a) + la.norm(b)

True

In [28]:
la.norm(a) >= 0

True

In [29]:
print(la.norm(np.zeros(shape=(2,))))
a == 0

0.0


array([False, False, False])

###4.1.8 Inner product & Norm

$u\cdot v = ||u||\,||v||\,cos\theta$

This formula showes that the inner product is in propotional to length of the vectors and $cos$ of angle between the vectors.

1.   When both of Vectors are heading the same direction($\theta = 0^\circ$), the inner product has the max value.
2.   When two Vectors are perpendicular($\theta=90^\circ$), the inner product is 0.
3.   When two Vectors are heading completely opposite directions($\theta = 180^\circ$), the inner product has the min value.




###4.1.9 Vector linear dependence
It is a funcamental concept in linear algebra that describes the relationship between bectors in a vector space.

A set of vectors ${v_q, v_2, ...,v_n}$ is linearly dependent if there exist scalars $c_1,c_2,...,c_n$, not all zero, such that:

$c_1v_1 + c_2v_2 + ... +c_nv_n = 0$

For example:

$a_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, a_2 = \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix}, a_3 = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}$

Clearly, $a_3 = a_1 + a_2$, therefore the vectors above are linearly dependent.
<br><br>

####Linear independence
In other words, at least one vector in the set can be expressed as a linear combination of the others.

Conversely, a set of vectors is linearly independent if the only solution to:

$c_1v_1 + c_2v_2 + ... + c_nv_n$
is $c_1 = c_2 = ... = c_n = 0$

for example:

$a_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, a_2 = \begin{pmatrix} 0 \\ -1 \\ 0 \end{pmatrix}, a_3 = \begin{pmatrix} -1 \\ 0 \\ 1 \end{pmatrix}$

From $\beta_1a_1 + \beta_2a_2 + \beta_3a_3 = 0$, we have $ \beta+1 - \beta_3 = 0, -\beta_2 = 0,$ and $\beta_3 = 0$.Therefore, all $\beta$ values are 0 and vectors above are linearly independent.


####4.1.9.1 basis

A basis in $n$ linearly independent vectors in $n$ dimensions. In other words, two vectors which are linearly independent in two-dimensional vector space. When there are another vectors, they can be expressend as a linear combination of two other linearly independent vectors.

So, If $n$ dimentional vector $a_1, \ldots,a_n$ is a basis, Any $n$ dimensional vector $x$ can be expressed as a linear combination of bases.

**Example**

Express $x = \begin{bmatrix} 0.3 \\ 0.7 \end{bmatrix}$ as a linear combination of $a1 = \begin{bmatrix} 2 \\ 0 \end{bmatrix}, a2 = \begin{bmatrix} 0 \\ 3 \end{bmatrix}$

<br>Answer:<br>
$\beta_1\begin{bmatrix} 2 \\ 0 \end{bmatrix} + \beta_2\begin{bmatrix} 0 \\ 3 \end{bmatrix} = \begin{bmatrix} 0.3 \\ 0.7 \end{bmatrix}$

So,
$\,2\beta_1 =0.3, 3\beta_2 = 0.7$

Therefore, $\begin{bmatrix} \beta_1 \\ \beta_2 \end{bmatrix} = \begin{bmatrix} \frac{0.3}{2} \\ \frac{0.7}{3} \end{bmatrix}$.

####4.1.9.2 Orthonormal vector

$a_1 \cdots a_n$ being orthonormal means that they form a set of vectors that are mutually orthogonal while simultaneously each having a length of 1.

In the other words, when $i = j$, the dot product, $a_i^T \cdot a_j = 1$, and when $i \neq j$, the dot product, $a_i^T \cdot a_j = 0$

**example**

$a_1 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix},
a_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix},
a_3 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix}$

In [40]:
a1 = np.array([0, 0, 1]).reshape(-1, 1)
a2 = 1/np.sqrt(2) * np.array([1, 1, 0]).reshape(-1, 1)
a3 = 1/np.sqrt(2) * np.array([1, -1, 0]).reshape(-1, 1)

A = np.concatenate((a1, a2, a3), axis = 1)

np.round(A.T @ A, 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

#4.2 Express of matrix
Matirx is an array that is divided with row and column.

You can define elements of matrix as numbers or characters

$A = \begin{bmatrix}
-1.09 & 1 & 0.28 & -1.51 \\
 -0.58 & 1.65 & -2.43 & -0.43 \\
  1.27 & -0.87 & -0.68 & -0.09 \\
   1.49 & -0.64 & -0.44 & -0.43
   \end{bmatrix}$

$B = \begin{bmatrix}
a & c \\
b & d
\end{bmatrix}$

In [41]:
A = np.array(np.random.RandomState(123).normal(size = 16)).reshape(4, 4)
A.round(3)

array([[-1.086,  0.997,  0.283, -1.506],
       [-0.579,  1.651, -2.427, -0.429],
       [ 1.266, -0.867, -0.679, -0.095],
       [ 1.491, -0.639, -0.444, -0.434]])

###4.2.1 Size of matrix

Size of matrix is defined with count of row & column. In 4.2, A matrix has 4 rows and 4 columns, so it is called **4 by 4** matrix.

Also you can express like $A_{n\times p}$

Especially, a matrix which has the same count of rows and columns is called **square matrix**.

In [42]:
A = np.array(np.random.RandomState(123).normal(size = 12)).reshape(3, 4)
A.shape

(3, 4)

###4.2.2 Row vector and Column vector

A vector which consists of row only is called row vector, and a vector which consists of column only is called column vector.

**Example**

$A = \begin{bmatrix}
3 & 3 & 7 & 2\\
4 & 11 & 10 & 7 \\
2 & 1 & 2 & 10
\end{bmatrix}$

In this matrix, $\begin{bmatrix}3 \\ 4 \\ 2\end{bmatrix}$ is one of the column vectors, and $\begin{bmatrix}3 & 3 & 7 & 2\end{bmatrix}$ is one of the row vectors.

In [43]:
A = np.array(np.random.RandomState(123).randint(1, 12, size = 12)).reshape(3, 4)
A

array([[ 3,  3,  7,  2],
       [ 4, 11, 10,  7],
       [ 2,  1,  2, 10]])

In [46]:
#Row vector
display(A[:, 0])
display(A[:, 1])
display(A[:, 2])
display(A[:, 3])

array([3, 4, 2])

array([ 3, 11,  1])

array([ 7, 10,  2])

array([ 2,  7, 10])

In [47]:
#Column vector
display(A[0, :])
display(A[1, :])
display(A[2, :])

array([3, 3, 7, 2])

array([ 4, 11, 10,  7])

array([ 2,  1,  2, 10])

###4.2.3 Notation of matrix

Matrix is expressed with box brackets or parentheses like below.

$A = \begin{bmatrix}
a_{1\,1} & a_{1\,2} & \cdots & a_{1\, p}\\
a_{2\,1} & a_{2\,2} & \cdots & a_{2\, p}\\
\cdot & \cdot & \cdots & \cdot\\
a_{n\,1} & a_{n\,2} & \cdots & a_{n\, p}
\end{bmatrix}
=
\begin{pmatrix}
a_{1\,1} & a_{1\,2} & \cdots & a_{1\, p}\\
a_{2\,1} & a_{2\,2} & \cdots & a_{2\, p}\\
\cdot & \cdot & \cdots & \cdot\\
a_{n\,1} & a_{n\,2} & \cdots & a_{n\, p}
\end{pmatrix} = (a_{i\,j}) \in \mathbb{R}^{n\times p}$
<br><br>
In the array below, $a_{1\,1} = 3$,  $a_{2\,4} = 7$

In [48]:
display(A[0, 0])
display(A[1, 3])

3

7