<a href="https://colab.research.google.com/github/JJUN1012/Probability-and-Statistics-with-Python/blob/main/4_vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This document is typed with python and $\LaTeX$

###import necessary packages for study

In [3]:
import numpy as np
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

#check version
print(np.__version__)
print(scipy.__version__)

1.26.4
1.13.1


#4.1 express of vector

In [4]:
v =  np.array([0.61, 0.93, 0.24, 0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [5]:
print(v[0])
print(v[3])

0.61
0.27


###4.1.1 size(dimention, length) of vector

In [6]:
v.shape

(4,)

###4.1.2 subvector

In [7]:
v_sub = v[0:2]#v[0]-v[1]
v_sub

array([0.61, 0.93])

###4.1.3 special vectors
A zero vector is a vector where all elements are zero.

In [8]:
size = 3
zeros = np.zeros(shape = (size,))
zeros

array([0., 0., 0.])

A vector with one element equal to 1 and all others equal to 0 is called a unit vector.

Unit vectors are specially denoted using the $\mathbf{e}$ notation.

$\mathbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$
 $\mathbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$
 $\mathbf{e}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$


In [9]:
e = np.zeros(shape = (3,))

i = 1 #locate 1

e[i] = 1
e

array([0., 1., 0.])

A one vector is a vector where all elements are one.

In [10]:
one = np.ones(shape = (size,))
one

array([1., 1., 1.])

###4.1.4 geometric meaning of vectors

In two or three-dimensional space, vectors can be interpreted as:

* Displacements from one point to another
* Forces acting in a particular direction
* Velocities with both speed and direction
* Any quantity that requires both magnitude and direction to be fully described

###4.1.5 Vector Calculation
####4.1.5.1 Vector Addition
Addition of two vectors of the same size is defined as the sum of their corresponding elements.

$\begin{bmatrix} 1 \\ 3 \end{bmatrix} + \begin{bmatrix} 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 4 \\ 4 \end{bmatrix}$

The addition operation satisfies the commutative law and the associative law.

In [11]:
a = np.array([1, 3])
b = np.array([3, 1])
a + b

array([4, 4])

In [12]:
#commutative law
a + b == b + a

array([ True,  True])

In [13]:
#associative law
d = np.array([1, 2])
(a + b) + d == a + (b + d)

array([ True,  True])

####4.1.5.2 Vector subtraction
$\begin{bmatrix} 3 \\ 1 \end{bmatrix} - \begin{bmatrix} 1 \\ 3 \end{bmatrix} = \begin{bmatrix} 2 \\ -2 \end{bmatrix}$

In [14]:
b - a

array([ 2, -2])

####4.1.5.3 Scalar-Vector multiplication
Multiply all elments of a vector by scalar

$\begin{bmatrix} \dfrac{1}{2} \end{bmatrix} \begin{bmatrix} 2 \\ 3 \end{bmatrix} = \begin{bmatrix} 1 \\ 1.5 \end{bmatrix}$  

$\begin{bmatrix} 2 \\ 3 \end{bmatrix} \begin{bmatrix} \dfrac{1}{2} \end{bmatrix} = \begin{bmatrix} 1 \\ 1.5 \end{bmatrix}$  

In [15]:
alpha = 1/2
a = np.array([2, 3])
alpha * a

array([1. , 1.5])

In [16]:
#commutative law
a * alpha == alpha * a

array([ True,  True])

In [17]:
#distributive law
beta = 0.7
(alpha + beta) * a == alpha * a + beta * a

array([ True,  True])

####4.1.5.4 Linear Combination
Linear combination is a fundamental concept in linear algebra that refers to the weighted sum of vectors.

a₁v₁ + a₂v₂ + ... + aₙvₙ

###4.1.6 inner product
$a^Tb = \sum_{i=1}^{n} a_ib_i$

T is a notation for transpose

it can be also expressed with $a \cdot b ,  < a,  b >$

$\begin{bmatrix} -1 \\ 2 \\ 3\end{bmatrix}^T \begin{bmatrix} 1 \\ -2 \\ 4 \end{bmatrix} = sum \begin{bmatrix} -1 \\ -4 \\ 12 \end{bmatrix} = 7$

In [18]:
a =  np.array([-1, 2, 3])
b =  np.array([1, -2, 4])

print(a * b)
np.sum (a * b)

[-1 -4 12]


7

In [19]:
#with function
print(np.inner(a, b))
print(np.dot(a, b))

7
7


In [20]:
#commutative law
np.dot(a, b) == np.dot(b, a)

True

In [21]:
#associative law
alpha = 0.5
np.dot(alpha * a, b) == alpha * np.dot(a, b)

True

In [22]:
#distributive law
c = np.array([1, 2, 3])
np.dot(a + b, c) == np.dot(a, c) + np.dot(b, c)

True

some usuage of inner product
1. $1^Ta = a_1 + \ldots +a_n = \sum_{i=1}^{n} a_i$
2. $\frac{1}{n}1^Ta = \frac{1}{n}(a_1 + \ldots + a_n) = \bar{a}$
3. $a^Ta = a^2_1 + \ldots + a^2_n$

In [23]:
a = np.array([1, 2, 3])
size = len(a)
ones = np.ones(shape=(size, ))
np.dot(ones, a)

6.0

In [24]:
np.dot(ones, a) / len(a)

2.0

In [25]:
np.dot(a, a)

14

###4.1.7 Vector norm
This is Euclidean norm of Vector.
Norm means length or magnitude of vector

$||a||_2 = \sqrt{a^Ta} = \sqrt{a^2_1 + \ldots + a^2_n}$

example

$\bigg|\bigg|\begin{bmatrix} 2 \\ 3 \end{bmatrix}\bigg|\bigg|= \sqrt{\begin{bmatrix}2 \\ 3 \end{bmatrix}^T\begin{bmatrix}2 \\ 3 \end{bmatrix}} = \sqrt{sum\begin{bmatrix}4 \\ 9 \end{bmatrix}} = \sqrt{13} = 3.606...$

In [26]:
a = np.array([2, 3])
la.norm(a)

3.605551275463989

A norm satisfies the following properties.

* $||\beta a|| = |\beta|\,||a||$
* $||a + b|| \leq ||a|| + ||b||$
* $||a|| \geq 0$
* $||a|| = 0 \Rightarrow a = 0$

In [27]:
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

beta = 0.5
la.norm(beta * a) == np.abs(beta) * la.norm(a)

True

In [28]:
la.norm(a + b) <= la.norm(a) + la.norm(b)

True

In [29]:
la.norm(a) >= 0

True

In [30]:
print(la.norm(np.zeros(shape=(2,))))
a == 0

0.0


array([False, False, False])

###4.1.8 Inner product & Norm

$u\cdot v = ||u||\,||v||\,cos\theta$

This formula showes that the inner product is in propotional to length of the vectors and $cos$ of angle between the vectors.

1.   When both of Vectors are heading the same direction($\theta = 0^\circ$), the inner product has the max value.
2.   When two Vectors are perpendicular($\theta=90^\circ$), the inner product is 0.
3.   When two Vectors are heading completely opposite directions($\theta = 180^\circ$), the inner product has the min value.




###4.1.9 Vector linear dependence
It is a funcamental concept in linear algebra that describes the relationship between bectors in a vector space.

A set of vectors ${v_q, v_2, ...,v_n}$ is linearly dependent if there exist scalars $c_1,c_2,...,c_n$, not all zero, such that:

$c_1v_1 + c_2v_2 + ... +c_nv_n = 0$

For example:

$a_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, a_2 = \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix}, a_3 = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}$

Clearly, $a_3 = a_1 + a_2$, therefore the vectors above are linearly dependent.
<br><br>

####Linear independence
In other words, at least one vector in the set can be expressed as a linear combination of the others.

Conversely, a set of vectors is linearly independent if the only solution to:

$c_1v_1 + c_2v_2 + ... + c_nv_n$
is $c_1 = c_2 = ... = c_n = 0$

for example:

$a_1 = \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix}, a_2 = \begin{pmatrix} 0 \\ -1 \\ 0 \end{pmatrix}, a_3 = \begin{pmatrix} -1 \\ 0 \\ 1 \end{pmatrix}$

From $\beta_1a_1 + \beta_2a_2 + \beta_3a_3 = 0$, we have $ \beta+1 - \beta_3 = 0, -\beta_2 = 0,$ and $\beta_3 = 0$.Therefore, all $\beta$ values are 0 and vectors above are linearly independent.


####4.1.9.1 basis

A basis in $n$ linearly independent vectors in $n$ dimensions. In other words, two vectors which are linearly independent in two-dimensional vector space. When there are another vectors, they can be expressend as a linear combination of two other linearly independent vectors.

So, If $n$ dimentional vector $a_1, \ldots,a_n$ is a basis, Any $n$ dimensional vector $x$ can be expressed as a linear combination of bases.

**Example**

Express $x = \begin{bmatrix} 0.3 \\ 0.7 \end{bmatrix}$ as a linear combination of $a1 = \begin{bmatrix} 2 \\ 0 \end{bmatrix}, a2 = \begin{bmatrix} 0 \\ 3 \end{bmatrix}$

<br>Answer:<br>
$\beta_1\begin{bmatrix} 2 \\ 0 \end{bmatrix} + \beta_2\begin{bmatrix} 0 \\ 3 \end{bmatrix} = \begin{bmatrix} 0.3 \\ 0.7 \end{bmatrix}$

So,
$\,2\beta_1 =0.3, 3\beta_2 = 0.7$

Therefore, $\begin{bmatrix} \beta_1 \\ \beta_2 \end{bmatrix} = \begin{bmatrix} \frac{0.3}{2} \\ \frac{0.7}{3} \end{bmatrix}$.

####4.1.9.2 Orthonormal vector

$a_1 \cdots a_n$ being orthonormal means that they form a set of vectors that are mutually orthogonal while simultaneously each having a length of 1.

In the other words, when $i = j$, the dot product, $a_i^T \cdot a_j = 1$, and when $i \neq j$, the dot product, $a_i^T \cdot a_j = 0$

**example**

$a_1 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix},
a_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix},
a_3 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix}$

In [31]:
a1 = np.array([0, 0, 1]).reshape(-1, 1)
a2 = 1/np.sqrt(2) * np.array([1, 1, 0]).reshape(-1, 1)
a3 = 1/np.sqrt(2) * np.array([1, -1, 0]).reshape(-1, 1)

A = np.concatenate((a1, a2, a3), axis = 1)

np.round(A.T @ A, 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

#4.2 Express of matrix
Matirx is an array that is divided with row and column.

You can define elements of matrix as numbers or characters

$A = \begin{bmatrix}
-1.09 & 1 & 0.28 & -1.51 \\
 -0.58 & 1.65 & -2.43 & -0.43 \\
  1.27 & -0.87 & -0.68 & -0.09 \\
   1.49 & -0.64 & -0.44 & -0.43
   \end{bmatrix}$

$B = \begin{bmatrix}
a & c \\
b & d
\end{bmatrix}$

In [32]:
A = np.array(np.random.RandomState(123).normal(size = 16)).reshape(4, 4)
A.round(3)

array([[-1.086,  0.997,  0.283, -1.506],
       [-0.579,  1.651, -2.427, -0.429],
       [ 1.266, -0.867, -0.679, -0.095],
       [ 1.491, -0.639, -0.444, -0.434]])

###4.2.1 Size of matrix

Size of matrix is defined with count of row & column. In 4.2, A matrix has 4 rows and 4 columns, so it is called **4 by 4** matrix.

Also you can express like $A_{n\times p}$

Especially, a matrix which has the same count of rows and columns is called **square matrix**.

In [33]:
A = np.array(np.random.RandomState(123).normal(size = 12)).reshape(3, 4)
A.shape

(3, 4)

###4.2.2 Row vector and Column vector

A vector which consists of row only is called row vector, and a vector which consists of column only is called column vector.

**Example**

$A = \begin{bmatrix}
3 & 3 & 7 & 2\\
4 & 11 & 10 & 7 \\
2 & 1 & 2 & 10
\end{bmatrix}$

In this matrix, $\begin{bmatrix}3 \\ 4 \\ 2\end{bmatrix}$ is one of the column vectors, and $\begin{bmatrix}3 & 3 & 7 & 2\end{bmatrix}$ is one of the row vectors.

In [34]:
A = np.array(np.random.RandomState(123).randint(1, 12, size = 12)).reshape(3, 4)
A

array([[ 3,  3,  7,  2],
       [ 4, 11, 10,  7],
       [ 2,  1,  2, 10]])

In [35]:
#Row vector
display(A[:, 0])
display(A[:, 1])
display(A[:, 2])
display(A[:, 3])

array([3, 4, 2])

array([ 3, 11,  1])

array([ 7, 10,  2])

array([ 2,  7, 10])

In [36]:
#Column vector
display(A[0, :])
display(A[1, :])
display(A[2, :])

array([3, 3, 7, 2])

array([ 4, 11, 10,  7])

array([ 2,  1,  2, 10])

###4.2.3 Notation of matrix

Matrix is expressed with box brackets or parentheses like below.

$A = \begin{bmatrix}
a_{1\,1} & a_{1\,2} & \cdots & a_{1\, p}\\
a_{2\,1} & a_{2\,2} & \cdots & a_{2\, p}\\
\cdot & \cdot & \cdots & \cdot\\
a_{n\,1} & a_{n\,2} & \cdots & a_{n\, p}
\end{bmatrix}
=
\begin{pmatrix}
a_{1\,1} & a_{1\,2} & \cdots & a_{1\, p}\\
a_{2\,1} & a_{2\,2} & \cdots & a_{2\, p}\\
\cdot & \cdot & \cdots & \cdot\\
a_{n\,1} & a_{n\,2} & \cdots & a_{n\, p}
\end{pmatrix} = (a_{i\,j}) \in \mathbb{R}^{n\times p}$
<br><br>
In the array below, $a_{1\,1} = 3$,  $a_{2\,4} = 7$

In [37]:
display(A[0, 0])
display(A[1, 3])

3

7

###4.2.4 Matrix operation

####4.2.4.1 Matrix addition

Addition of matrices of the same size is defined as follows.

When $A = (a_{ij}), B = (b_{ij})$,

$A + B = (a_{ij} + b_{ij})$

It is the sum of the balues of the elements at the correspoinding position.

In [38]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(3, 9).reshape(2, 3)
display(A)
display(B)
A + B

array([[1, 2, 3],
       [4, 5, 6]])

array([[3, 4, 5],
       [6, 7, 8]])

array([[ 4,  6,  8],
       [10, 12, 14]])

This addition also obeys the commutative and associative laws.

In [39]:
#Commutative law
A + B == B + A

array([[ True,  True,  True],
       [ True,  True,  True]])

In [40]:
#Associative law
C = np.arange(5, 11).reshape(2, 3)
(A + B) + C == A + (B + C)

array([[ True,  True,  True],
       [ True,  True,  True]])

####4.2.4.2 Multiplication of scalar and matrix

When $A = (a_{ij}), c \in \mathbb{R}$

$cA = (ca_{ij})$

In the other words, this multiplies each element by the scalar $c$

$0.1 \times \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix} = \begin{bmatrix}0.1 & 0.2 & 0.3 \\ 0.4 & 0.5 & 0.6\end{bmatrix}$

In [41]:
c = 0.1
c * A

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [42]:
#Commutative law
c * A == A * c

array([[ True,  True,  True],
       [ True,  True,  True]])

####4.2.4.3 Transpose of a Matrix

Basically, it means that exchanges of position of rows and columns.

For example, $\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix}^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6\end{bmatrix}$

In [43]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

It has the following properties:



1.  $(A + B)^T = A^T + B^T$
2.  $(cA)^T = cA^T$



In [44]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(3, 9).reshape(2, 3)

A.T + B.T == (A + B).T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [45]:
c = 0.1
(c * A).T == c * A.T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

####4.2.4.4 Matrix multiplication

It is defined as below

$AB = (c_{il}) = (\sum\limits_{r=1}^p a_{ir} b_{rl}),\; i = 1, \ldots, n, \; l = 1,\ldots,m$

As you can see in definition, count of columns of $A$ and count of rows of $B$ must be the same. Size of the result matrix is count of rows of $A$ and count of columns of $B$.

$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix}\begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\end{bmatrix} = \begin{bmatrix} 22 & 28 \\ 49 & 64\end{bmatrix}$

In [46]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
A @ B

array([[22, 28],
       [49, 64]])

In [53]:
np.matmul(A, B)

array([[22, 28],
       [49, 64]])

Multiplication of Matrix doesn't meet commutative law.

In [58]:
A = np.arange(1, 5).reshape(2, 2)
display(A)
B = np.arange(5, 9).reshape(2, 2)
display(B)

display('A @ B: ', A @ B)
display('B @ A: ', B @ A)

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

'A @ B: '

array([[19, 22],
       [43, 50]])

'B @ A: '

array([[23, 34],
       [31, 46]])

For matrix muliplication, the transpose operator holds as follows:

$(AB)^T = B^TA^T$

Because, $((AB)^T)_{ij} = \sum_rb_{ri}a_{rj}$ and $(B^TA^T)_{ij} = \sum_rb_{ri}a_{rj}$

In [59]:
#example
(A @ B).T

array([[19, 43],
       [22, 50]])

In [60]:
B.T @ A.T

array([[19, 43],
       [22, 50]])

####4.2.4.5 Submatrix

A submatrix is ​​a matrix that can be obtained by deleting arbitrary rows and columns from any matrix A.

$A = \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 &6\\7&8&9\\10&11&12\end{bmatrix}$

$A_{1:2, 2:3} = \begin{bmatrix}2 & 3 \\ 5 & 6\end{bmatrix}$
$A_{:, 2:3} = \begin{bmatrix}2 & 3 \\ 5 & 6 \\ 8&9 \\ 11&12\end{bmatrix}$
$A_{(1,3), (2,3)} = \begin{bmatrix}2 & 3 \\ 8 & 9\end{bmatrix}$

In [63]:
A = np.arange(1, 13).reshape(4, 3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
A[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [65]:
A[:, 1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [67]:
A[[0, 2], :][:, [1, 2]]

array([[2, 3],
       [8, 9]])

###4.2.5 Special matrix

Zero Matrix

$\begin{bmatrix}0&0&0\\0&0&0\\0&0&0\end{bmatrix}$

Identity Matrix:
Only the diagonal elements have values ​​of 1, the rest are all 0.

$I_3 = \begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}$

Diagonal Matrix:
All elements except the diagonal values ​​have values ​​of 0.

$D_3 = \begin{bmatrix}1&0&0\\0&2&0\\0&0&3\end{bmatrix}$

In [68]:
size = 3
np.zeros(shape=(size, size))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.identity(n = size)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Triangular Matrix: It is a matrix in which all sides of the diagonal are 0. If lower is all 0, it is called an **upper triangular matrix**, and the opposite is called a **lower triangular matrix**.

$T^{upper} = \begin{bmatrix}1&2&3\\0&2&7\\0&0&5\end{bmatrix}$




In [74]:
np.triu([[1, 2, 3],[1, 2, 7],[7, 8, 5]], k= 0)

array([[1, 2, 3],
       [0, 2, 7],
       [0, 0, 5]])

Orthogonal Matrix: each column or ros is an orthonormal vector.

$A^TA = AA^T = I$

In [75]:
A = np.array([[1,0], [0, -1]])
A

array([[ 1,  0],
       [ 0, -1]])

In [76]:
A.T @ A

array([[1, 0],
       [0, 1]])

In [77]:
A @ A.T

array([[1, 0],
       [0, 1]])

#4.3 Linear Equation

Linear Equation means like below:

$a_1x_1 + a_2x_2 + \cdots + a_nx_n = b_1$

In here, $x_1, \cdots , x_p $ are variables, b_1 is a constant, and $a_1,\cdots ,a_n are coefficients.$

For example,

$x_1 + x_2 = 5$

$\frac{1}{2}x_1 - x_2 = 2$

It can be expressed with matrix like below:

$\begin{bmatrix}1 & 1 \\ \frac{1}{2} & -1\end{bmatrix} \begin{bmatrix}x_1\\x_2\end{bmatrix} =\begin{bmatrix}5\\2\end{bmatrix}$

So, you can express it in form of $Ax = b$. In linear equation matrix like this, you can evaluate solution with addition or subtraction method.